version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: helpdesk_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: helpdesk
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./helpdesk_backend
    container_name: helpdesk_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/helpdesk
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - JWT_EXPIRATION=86400000
    depends_on:
      - db

  frontend:
    build:
      context: ./helpdesk_frontend
      args:
        - VITE_API_URL=http://74.249.99.138:8080
    container_name: helpdesk_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: